####
# mvn package
# docker build -f src/main/docker/Dockerfile.jvm -t quarkus/amazon-lambda-dynamodb-jvm .
# docker run -i --rm -p 8080:8080 quarkus/amazon-lambda-dynamodb-jvm
###

FROM fabric8/java-jboss-openjdk8-jdk
ENV JAVA_OPTIONS=-Dquarkus.http.host=0.0.0.0
COPY target/lib/* /deployments/lib/
COPY target/*-runner.jar /deployments/app.jar
ENTRYPOINT [ "/deployments/run-java.sh" ]