####
# mvn package -Pnative -Dnative-image.docker-build=true
# docker build -f src/main/docker/Dockerfile.native -t quarkus/amazon-lambda-dynamodb .
# docker run -i --rm -p 8080:8080 quarkus/amazon-lambda-dynamodb
###

FROM registry.fedoraproject.org/fedora-minimal
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]